services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydb
    volumes:
      - ./scripts/db-init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
  auth-server:
    build:
      context: .
      dockerfile: ./containerfile
    ports:
      - "3333:3333"
    working_dir: /app
    volumes:
      - "./packages/auth-server:/app/packages/auth-server"
      - "./package.json:/app/package.json"
      - "./package-lock.json:/app/package-lock.json"
    command: npm run -w @hasura-demo/auth-server start

volumes:
  postgres_data: