services:
  app_mydb:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.mydb
    environment:
      CONNECTION_URI: $APP_MYDB_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_MYDB_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MYDB_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MYDB_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4879:8080
